spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/imob
    username: sa_imob
    password: imob_pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
dotenv:
  enabled: true
  locations:
    - file:./.env

  